var fileDir=[
	{	
		"fileType":"folder",
		"fileName":"网络编程上机",
		"level":0,
		"fileSize":2.0,
		"date":"2015.11.5",
		"children":[
			{
				"fileType":"doc",
				"fileName":"实验报告封面.doc",
				"level":1,
				"fileSize":2.0,
				"date":"2015.11.5",
				"children":null
			},
			{
				"fileType":"doc",
				"fileName":"多点聊天室.doc",
				"level":1,
				"fileSize":2.0,
				"date":"2015.11.5",
				"children":null
			},
			{
				"fileType":"folder",
				"fileName":"web上机",
				"level":1,
				"fileSize":2.0,
				"date":"2015.11.5",
				"children":[
					{
						"fileType":"doc",
						"fileName":"web上机01.doc",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					}
				]
			}
		],
	},
	{
		"fileType":"folder",
		"fileName":"前端学习",
		"level":0,
		"fileSize":2.0,
		"date":"2015.11.5",
		"children":[
			{
				"fileType":"folder",
				"fileName":"RejectJS国语",
				"level":1,
				"fileSize":2.0,
				"date":"2015.11.5",
				"children":[
					{
						"fileType":"folder",
						"fileName":"RejectJS路由",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":[
							{
								"fileType":"video",
								"fileName":"router01.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"router02.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"router03.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"router04.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"router05.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"router06.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							}
						]
					},
					{
						"fileType":"folder",
						"fileName":"RejectJS基础",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":[
							{
								"fileType":"video",
								"fileName":"react01.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"react02.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"react03.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"react04.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"react05.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"react06.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							},
							{
								"fileType":"video",
								"fileName":"react07.mp4",
								"level":3,
								"fileSize":2.0,
								"date":"2015.11.5",
								"children":null

							}
						]
					}
				]
			},
			{
				"fileType":"folder",
				"fileName":"商城项目制作",
				"level":1,
				"fileSize":2.0,
				"date":"2015.11.5",
				"children":[
					{
						"fileType":"rar",
						"fileName":"素材文件.rar",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					},
					{
						"fileType":"rar",
						"fileName":"课件1-7.rar",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					},
					{
						"fileType":"video",
						"fileName":"mzsc01.mp4",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					},
					{
						"fileType":"video",
						"fileName":"mzsc02.mp4",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					},
					{
						"fileType":"video",
						"fileName":"mzsc03.mp4",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					},
					{
						"fileType":"video",
						"fileName":"mzsc04.mp4",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					},
					{
						"fileType":"video",
						"fileName":"mzsc05.mp4",
						"level":2,
						"fileSize":2.0,
						"date":"2015.11.5",
						"children":null
					},

				]
			}
		]
	}
]